name: env_py3
channels:
  - anaconda
  - defaults
dependencies:
  - keyring=13.2.1=py36_0
  - netcdf4=1.3.1=py36h8bd0532_2
  - pywin32=223=py36hfa6e2cd_1
  - spyder=3.3.1=py36_1
  - spyder-kernels=0.2.6=py36_0
  - vc=14.1=h0510ff6_3
  - vs2015_runtime=15.5.2=3
  - alabaster=0.7.10=py36hcd07829_0
  - asn1crypto=0.24.0=py36_0
  - astroid=1.6.2=py36_0
  - babel=2.5.3=py36_0
  - bleach=2.1.3=py36_0
  - bokeh=0.12.14=py36_0
  - ca-certificates=2018.03.07=0
  - cartopy=0.16.0=py36hbd42bde_0
  - certifi=2018.8.24=py36_1
  - cffi=1.11.5=py36h945400d_0
  - chardet=3.0.4=py36h420ce6e_1
  - click=6.7=py36hec8c647_0
  - cloudpickle=0.5.2=py36_1
  - colorama=0.3.9=py36h029ae33_0
  - cryptography=2.2.1=py36hfa6e2cd_0
  - curl=7.58.0=h7602738_0
  - cycler=0.10.0=py36h009560c_0
  - cytoolz=0.9.0.1=py36hfa6e2cd_0
  - dask=0.17.2=py36_0
  - dask-core=0.17.2=py36_0
  - decorator=4.2.1=py36_0
  - distributed=1.21.4=py36_0
  - docutils=0.14=py36h6012d8f_0
  - entrypoints=0.2.3=py36hfd66bb0_2
  - expat=2.2.5=hcc4222d_0
  - freetype=2.8=h51f8f2c_1
  - freexl=1.0.5=hfa6e2cd_0
  - gdal=2.2.2=py36hcebd033_1
  - geos=3.6.2=h9ef7328_2
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.1=h98b8871_1
  - heapdict=1.0.0=py36_2
  - html5lib=1.0.1=py36h047fa9f_0
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - idna=2.6=py36h148d497_1
  - imageio=2.3.0=py36_0
  - imagesize=1.0.0=py36_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py36_0
  - ipython=6.2.1=py36h9cf0123_1
  - ipython_genutils=0.2.0=py36h3c5d0ee_0
  - ipywidgets=7.1.2=py36_0
  - isort=4.3.4=py36_0
  - jedi=0.11.1=py36_1
  - jinja2=2.10=py36h292fed1_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=2.6.0=py36h7636477_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36h6d89b47_1
  - jupyter_core=4.4.0=py36h56e9d50_0
  - kealib=1.4.7=ha5b336b_5
  - kiwisolver=1.0.1=py36h12c3424_0
  - krb5=1.14.2=h63dfc2a_6
  - lazy-object-proxy=1.3.1=py36hd1c21d2_0
  - libboost=1.65.1=he51fdeb_4
  - libcurl=7.58.0=h7602738_0
  - libgdal=2.2.2=h2727f2b_1
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=hc65d273_3
  - libnetcdf=4.4.1.1=h825a56a_8
  - libpng=1.6.34=h79bbb47_0
  - libpq=9.6.6=hfe3f2bf_0
  - libspatialite=4.3.0a=h383548d_18
  - libssh2=1.8.0=hd619d38_4
  - libtiff=4.0.9=h0f13578_0
  - libxml2=2.9.7=h79bbb47_0
  - libxslt=1.1.32=hf6f1972_0
  - locket=0.2.0=py36hfed976d_1
  - lxml=4.2.1=py36heafd4d3_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.0=py36h0e26971_1
  - matplotlib=2.2.2=py36h153e9ff_0
  - mccabe=0.6.1=py36hb41005a_1
  - mistune=0.8.3=py36_0
  - mkl=2018.0.2=1
  - msgpack-python=0.5.5=py36he980bc4_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.3.1=py36h8dc0fde_0
  - nbformat=4.4.0=py36h3a5bc1b_0
  - networkx=2.1=py36_0
  - notebook=5.4.1=py36_0
  - numpy=1.14.2=py36h5c71026_0
  - numpydoc=0.7.0=py36ha25429e_0
  - olefile=0.45.1=py36_0
  - openjpeg=2.2.0=h29c51c3_2
  - openssl=1.0.2p=hfa6e2cd_0
  - owslib=0.16.0=py36_0
  - packaging=17.1=py36_0
  - pandas=0.22.0=py36h6538335_0
  - pandoc=1.19.2.1=hb2460c7_1
  - pandocfilters=1.4.2=py36h3ef6317_1
  - parso=0.1.1=py36hae3edee_0
  - partd=0.3.8=py36hc8e763b_0
  - patsy=0.5.0=py36_0
  - pickleshare=0.7.4=py36h9de030f_0
  - pillow=5.0.0=py36h0738816_0
  - pip=9.0.1=py36_5
  - proj4=4.9.3=hcf24537_7
  - prompt_toolkit=1.0.15=py36h60b8f86_0
  - psutil=5.4.3=py36hfa6e2cd_0
  - pycodestyle=2.3.1=py36h7cc55cd_0
  - pycparser=2.18=py36hd053e01_1
  - pyepsg=0.3.2=py36h6c744c8_0
  - pyflakes=1.6.0=py36h0b975d6_0
  - pygments=2.2.0=py36hb010967_0
  - pylint=1.8.3=py36_0
  - pyopenssl=17.5.0=py36h5b7d817_0
  - pyparsing=2.2.0=py36h785a196_1
  - pyproj=1.9.5.1=py36_0
  - pyqt=5.6.0=py36hb5ed885_5
  - pyshp=1.2.12=py36h9b5cf0b_0
  - pysocks=1.6.8=py36_0
  - python=3.6.4=h0c2934d_3
  - python-dateutil=2.7.0=py36_0
  - pytz=2018.3=py36_0
  - pywavelets=0.5.2=py36hc649158_0
  - pywinpty=0.5.1=py36_0
  - pyyaml=3.12=py36h1d1928f_1
  - pyzmq=17.0.0=py36hfa6e2cd_0
  - qt=5.6.2=vc14h6f8c307_12
  - qtawesome=0.4.4=py36h5aa48f6_0
  - qtconsole=4.3.1=py36h99a29a9_0
  - qtpy=1.4.0=py36_0
  - requests=2.18.4=py36h4371aae_1
  - rope=0.10.7=py36had63a69_0
  - scikit-image=0.13.1=py36hfa6e2cd_1
  - scikit-learn=0.19.1=py36h53aea1b_0
  - scipy=1.0.0=py36h1260518_0
  - send2trash=1.5.0=py36_0
  - setuptools=38.5.1=py36_0
  - shapely=1.6.4=py36h2a969d5_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.18.1=py36h9c25514_2
  - six=1.11.0=py36h4db2310_1
  - snowballstemmer=1.2.1=py36h763602f_0
  - sortedcontainers=1.5.9=py36_0
  - sphinx=1.7.1=py36_0
  - sphinxcontrib=1.0=py36hbbac3d2_1
  - sphinxcontrib-websupport=1.0.1=py36hb5e5916_1
  - sqlite=3.22.0=h9d3ae62_0
  - statsmodels=0.8.0=py36h6189b4c_0
  - tblib=1.3.2=py36h30f5020_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h2698cfe_0
  - tk=8.6.7=hcb92d03_3
  - toolz=0.9.0=py36_0
  - tornado=5.0=py36_0
  - traitlets=4.3.2=py36h096827d_0
  - typing=3.6.4=py36_0
  - urllib3=1.22=py36h276f60a_0
  - wcwidth=0.1.7=py36h3d5aa90_0
  - webencodings=0.5.1=py36h67c50ae_1
  - wheel=0.30.0=py36h6c3ec14_1
  - widgetsnbextension=3.1.4=py36_0
  - win_inet_pton=1.0.1=py36he67d7fd_1
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - wrapt=1.10.11=py36he5f5981_0
  - xerces-c=3.2.1=h27bfe9a_0
  - xz=5.2.3=h7c615d8_2
  - yaml=0.1.7=hc54c509_2
  - zict=0.1.3=py36h2d8e73e_0
  - zlib=1.2.11=h8395fce_2
prefix: C:\Anaconda\envs\env_py3

